# Generated by Django 2.1.5 on 2019-02-09 22:59

import catalog_app.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('room', djongo.models.fields.EmbeddedModelField(model_container=catalog_app.models.Room, model_form_class=catalog_app.models.RoomForm, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
